config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :jobs
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  match "/home/crawl",  via: [ :post] , as: :crawl
  get "/home/refresh-batch" => "home#crawl" , as: :refresh_batch
  get	"/home/web-address/:company_name" => "home#web_address", as: :web_address
  get "/home/get-domains/:batch_id" => "home#get_domains", as: :get_domains
  get "/home/get_company/:id" => "home#get_company", as: :get_company
  get "/home/get-emails/:id(/:job_id)" => "home#get_emails", as: :get_emails
  get "/home/get-all-emails/:batch_id" => "home#get_all_emails", as: :get_all_emails
  get "/home/csv-download/:batch_id" => "home#csv_download", as: :csv_download
  get "/home/job-csv-download/:job_id" => "home#job_csv_download", as: :job_csv_download
  get "/:batch_id"=> "home#index" , as: :active_batch
  post "/companies/import-csv" => "companies#import_csv", as: :import_csv



end

app/models/job.rb
class Job < ApplicationRecord
	belongs_to :company
	belongs_to :batch
	def has_emails?
		self.company.present? ? self.company.domain_search.present? ? self.company.domain_search.emails.present? ? true : false : false : false
	end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = Job.all
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
  end

  # GET /jobs/new
  def new
    @job = Job.new
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)

    respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:title, :company, :city, :state, :posted_date)
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_form.html.haml
= form_for @job do |f|
  - if @job.errors.any?
    #error_explanation
      %h2= "#{pluralize(@job.errors.count, "error")} prohibited this job from being saved:"
      %ul
        - @job.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :company
    = f.text_field :company
  .field
    = f.label :city
    = f.text_field :city
  .field
    = f.label :state
    = f.text_field :state
  .field
    = f.label :posted_date
    = f.text_field :posted_date
  .actions
    = f.submit 'Save'

app/views/jobs/edit.html.haml
%h1 Editing job

= render 'form'

= link_to 'Show', @job
\|
= link_to 'Back', jobs_path

app/views/jobs/index.html.haml
%h1 Listing jobs

%table
  %thead
    %tr
      %th Title
      %th Company
      %th City
      %th State
      %th Posted date
      %th
      %th
      %th

  %tbody
    - @jobs.each do |job|
      %tr
        %td= job.title
        %td= job.company
        %td= job.city
        %td= job.state
        %td= job.posted_date
        %td= link_to 'Show', job
        %td= link_to 'Edit', edit_job_path(job)
        %td= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Job', new_job_path

app/views/jobs/new.html.haml
%h1 New job

= render 'form'

= link_to 'Back', jobs_path

app/views/jobs/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @job.title
%p
  %b Company:
  = @job.company
%p
  %b City:
  = @job.city
%p
  %b State:
  = @job.state
%p
  %b Posted date:
  = @job.posted_date

= link_to 'Edit', edit_job_path(@job)
\|
= link_to 'Back', jobs_path