config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :jobs
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  match "/home/crawl",  via: [ :post] , as: :crawl
  get "/home/refresh-batch" => "home#crawl" , as: :refresh_batch
  get	"/home/web-address/:company_name" => "home#web_address", as: :web_address
  get "/home/get-domains/:batch_id" => "home#get_domains", as: :get_domains
  get "/home/get_company/:id" => "home#get_company", as: :get_company
  get "/home/get-emails/:id(/:job_id)" => "home#get_emails", as: :get_emails
  get "/home/get-all-emails/:batch_id" => "home#get_all_emails", as: :get_all_emails
  get "/home/csv-download/:batch_id" => "home#csv_download", as: :csv_download
  get "/home/job-csv-download/:job_id" => "home#job_csv_download", as: :job_csv_download
  get "/:batch_id"=> "home#index" , as: :active_batch
  post "/companies/import-csv" => "companies#import_csv", as: :import_csv



end

app/controllers/home_controller.rb
require 'crawl'
require 'csv'
class HomeController < ApplicationController
	before_action :set_agent, only: [:web_address , :crawl , :get_domains]
	before_action :set_batch, only: [:index , :get_domains ,:crawl]
	include Crawl
	def index
    @jobs = @active_batch.present? ? @active_batch.jobs : nil
	end
	def crawl
		# debugger
		get_data params
		respond_to do |format|
	      format.js { render :partial => "crawl" }
	    end
	end
	def get_domains
		@jobs = @active_batch.jobs.includes(:company)
		begin
			@jobs.each do |job|
				if !job.company.web_address.present?
					delay 1
					link = crawl_company_address job.company.name
					job.company.update(web_address: link)
				end
			end
			respond_to do |format|
				format.js { render :partial => "crawl"}
			end
		rescue => error
			$!.backtrace

			render js: "something_went_wrong(#{error.inspect});"
		end
	end
	def web_address
		link = crawl_company_address params[:company_name].to_s
		render js: "window.open('#{link}');"
	end
	def get_company
		@company = Company.find_by_id(params[:id])
		respond_to do |format|
			format.js
			format.html
		end
	end
	def get_emails
		@job = Job.find_by_id(params[:job_id])
		@company = Company.find(params[:id])
		@emails = get_domain_search_emails @company
		respond_to do |format|
			format.js
		end
	end
	def get_all_emails
		@batch = Batch.find_by_id(params[:batch_id])
		begin
			@batch.jobs.each do |job|
				get_domain_search_emails job.company
			end
			render js: "get_all_emails_success();"
		rescue => error
			render js: "something_went_wrong('Please make sure to get all domains first.');"
		end
		respond_to do |format|
			format.js
		end
	end
	def csv_download
    @batch = params[:batch_id].present? ? Batch.find_by_id(params[:batch_id]) : Batch.last
    @jobs = @batch.jobs.includes(company: {domain_search: :emails})
		respond_to do |format|
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"Contacts-list.csv\""
        headers['Content-Type'] ||= 'text/csv'

      end

		end
	end
	def job_csv_download
		@jobs = []
		job = Job.find_by_id(params[:job_id])
		puts "--------#{job.inspect}------"
		@jobs << job
		respond_to do |format|
			format.csv do
				headers['Content-Disposition'] = "attachment; filename=\"Contact-list.csv\""
				headers['Content-Type'] ||= 'text/csv'
				render 'csv_download'
			end
		end
	end
	private

	def get_data params
		puts "----------------------#{params.inspect}------------------------------"
		@jobs  = []
		home_page = @agent.get(job_site_url)
		search_form = home_page.forms.first
		search_form['q'] = params[:keyword]
		search_form['l'] = params[:city]
		results_page = search_form.submit
		@active_batch =  Batch.unscoped.find_or_create_by!(query: params[:keyword].downcase , city: params[:city].downcase)
		paginate_through results_page
		i = 2
		loop do
			break if results_page.link_with(text: "#{i.to_s}").nil?
			results_page = results_page.link_with(text: "#{i.to_s}").click
			# delay 1..2
			i = i + 1
			paginate_through results_page
		end
	end
	def paginate_through page
		get_page_data page
	end
	def get_page_data page
		page.search('#resultsCol .result').each do |job_section|
			company 	 	 = 		job_section.search(".company").text.strip
			city 		 		 = 		job_section.search(".location").text.strip
			posted_date  = 		job_section.search(".date").text.strip
			title 		   = 		job_section.search(".jobtitle").text.strip
			@company     =    Company.where(name: company).first_or_create do |comp|
				comp.batch_id = @active_batch.id
			end
			job          =    Job.find_or_create_by!(company_id: @company.id ,  batch_id: @active_batch.id, city: city , posted_date: posted_date , title: title)

			@jobs << job
		end
	end
	def crawl_company_address company_name
		google = @agent.get(search_engine_url)
		form  = google.forms.first
		form['q'] = company_name
		result = form.submit
		website_address = result.search('cite').first
		link = website_address.present? ? website_address.text.strip : ""
		link = "http://" + link if (link.present? and !link.include? 'http')
		link
	end
	def set_batch
    @batches =  Batch.all
		@unscoped_batches = Batch.unscoped.all
    @active_batch = params[:batch_id].present? ? Batch.unscoped.find_by_id(params[:batch_id]) :  @batches.last

	end
	def delay secs
		sleep rand(secs)
	end
	def get_domain_search_emails company
		begin
			if company.domain_search.present?
				emails = company.domain_search.emails
			else
				emails = company.create_domain_search
			end
		rescue
			company.update(invalid: true)
		end
		emails
	end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_crawl.js.erb
console.log("INSIDE")
$('#job_postings').html("<%= escape_javascript(render 'home/job_postings') %>")
$("#waiting_bar").modal('hide')

app/views/home/_get_company.html.haml
.modal-dialog{:role => "document"}
  .modal-content
    .modal-header
      %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
        %span{"aria-hidden" => "true"}
      %h4.modal-title Edit Company
    .modal-body
      =form_for(@company) do |f|
        = f.label :web_address
        = f.text_field :web_address , :label =>true
        = f.submit "submit"
    .modal-footer
      %button.btn.btn-default{"data-dismiss" => "modal", :type => "button"} Close
      %button.btn.btn-primary{:type => "button"} Save changes

app/views/home/_get_emails.html.haml
.modal-dialog{:role => "document"}
  .modal-content
    .modal-header
      %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
        %span{"aria-hidden" => "true"} x
      %h4.modal-title
        = (@emails.first.present?  ? @emails.first.domain_search.domain.to_s : "<empty>" )+ " Contacts"
      - if @jobs.present?
        .col-lg-10
        = (link_to "Download CSV", job_csv_download_path(@job.id, format: :csv) , class: " pull")
    .modal-body.emails-table
      %table.table.table-striped
        %thead
          %tr
            %th First Name
            %th Last Name
            %th Position
            %th Email
            %th Status
            %th Type
            %th Twitter Handle
            %th Source Page
        %tbody.test
          - @emails.each do |email|
            %tr
              %td= email.first_name
              %td= email.last_name
              %td= email.position
              %td= email.email
              %td= email.status
              %td= email.address_type
              %td= email.twitter
              %td= email.source_page

    .modal-footer

app/views/home/_job_postings.html.haml
.col-lg-4.pull-right
  .col-lg-3
    %label.control-label.pull-right.kk{for: "Batches"} Select Batch
  .col-lg-7
    = select_tag "Batches", options_from_collection_for_select(@unscoped_batches, "id", "search_params",@active_batch.present? ? @active_batch.id : ""),
     class: "form-control pull-right",onchange: "return get_batch(this);",:prompt => "Select Batch"
  .col-lg-2
    - if @active_batch.present?
      = link_to refresh_batch_path(keyword: @active_batch.query ,city: @active_batch.city),remote: :true,onclick: "return show_waiting_bar();", class: "btn btn-default" ,title: "Refresh Batch" do
        %span{class: "glyphicon glyphicon-refresh"}
%br
%br
.col-lg-6#settings

%br
- if @active_batch.present? and @active_batch.batch_type == "search"
  - @jobs = jobs if (!@jobs.present? and defined?jobs and jobs.present?)
  - if @jobs.present?
    = link_to "Get Domains" , get_domains_path(@active_batch.present? ? @active_batch.id : "") , class: "btn btn-danger pull-right" , remote: :true , onclick: "return show_waiting_bar();"
    = link_to "Get all Emails", get_all_emails_path(@active_batch.id), class: "btn btn-info pull-right" , remote: :true , onclick: "return show_waiting_bar();"
    =link_to "Download CSV" , csv_download_path(@active_batch.id, format: :csv) , class: "btn btn-primary pull-right"

    %h2.col-lg-6
      = @jobs.count
      Jobs for
      %i
        = @jobs.first.batch.search_params
        (
        = @jobs.first.batch.updated_at.strftime("%F %H:%M %p")
        )
    .col-lg-1

    %table.table.table-striped
      %thead
        %tr
          %th Sr#
          %th Job Title
          %th Company
          %th City
          %th Posted date
          %th Company Domain
          %th See Contacts
          %th CSV
      %tbody
        - @jobs.sort_by(&:posted_date).each_with_index do |job, index|
          - company_name = job.company.present?  ? job.company.name.present?  ?  job.company.name : "" : ""
          - company_id = job.company.present? ?  job.company.id : ""
          - klass = "danger" if (job.company.present? and job.company.invalid_address)
          %tr{class: "#{klass}"}
            %td= index + 1
            %td= job.title
            %td= company_name
            %td= job.city
            %td= job.posted_date
            %td
              = job.company.present?  ? (link_to job.company.web_address.to_s , job.company.web_address.to_s ,target: :_blank) : ""
              = job.company.present?  ? (link_to "Edit Company", edit_company_path(company_id, active_batch: @active_batch.id),remote: :true, class: "pull-right ") : ""
            %td
              = job.company.present?  ? job.company.web_address.present?  ? ( link_to "See Emails" ,get_emails_path(company_id , job.id), remote: :true ,onclick: "return show_waiting_bar();") : "" : ""
            %td
              = (link_to "Download", job_csv_download_path(job.id, format: :csv) , class: "") if job.has_emails?

    -#%br
- elsif @active_batch.present? and @active_batch.batch_type == "import"
  %h2.col-lg-6
    = @active_batch.companies.count
    Companies for import csv
    %i
      (
      = @active_batch.updated_at.strftime("%F %H:%M %p")
      )

  %table.table.table-striped
    %thead
      %tr
        %th Sr#
        -#%th Job Title
        %th Company
        -#%th City
        -#%th Posted date
        %th Company Domain
        %th See Contacts
        -#%th CSV
    %tbody
      - @active_batch.companies.sort_by(&:created_at).each_with_index do |company, index|
        -#- company_name = company.present?  ? company.name.present?  ?  job.company.name : "" : ""
        -#- company_id = job.company.present? ?  job.company.id : ""
        - klass = "danger" if (company.present? and company.invalid_address)
        %tr{class: "#{klass}"}
          %td= index + 1
          -#%td= job.title
          %td= company.name
          -#%td= job.city
          -#%td= job.posted_date
          %td
            = company.present?  ? (link_to company.web_address.to_s , company.web_address.to_s ,target: :_blank) : ""
            = company.present?  ? (link_to "Edit Company", edit_company_path(company.id, active_batch: @active_batch.id),remote: :true, class: "pull-right ") : ""
          %td
            = company.present?  ? company.web_address.present?  ? ( link_to "See Emails" ,get_emails_path(company.id , ""), remote: :true ,onclick: "return show_waiting_bar();") : "" : ""
          -#%td
            -#= (link_to "Download", job_csv_download_path(job.id, format: :csv) , class: "") if job.has_emails?

  %br

app/views/home/csv_download.csv.haml
-#<%- headers = ['Name', 'Email'] -%>
-#<%= CSV.generate_line headers %>
-#<%- @users.each do |user| -%>
-#<%= CSV.generate_line([user.name, user.email]) -%>
-#<%- end -%>

= ["Job Title" ,"Company", "City" , "Posted Data" ,"First Name" , "Last Name", "Position","Email" ,"Status", "Twitter","Email Type"].to_csv( row_sep: nil )
- @jobs.each do |job|
  -if job.company.present? and job.company.domain_search.present?
    - job.company.domain_search.emails.each do |email|
      = [job.title.present? ? job.title.tr('^A-Za-z0-9 ', '') : "-",
         job.company.name.present?  ? job.company.name.tr('^A-Za-z0-9 ', '') : "",
         job.city.present? ? job.city.tr('^A-Za-z0-9 ', ''): "-",
         job.posted_date.present? ?  job.posted_date.tr('^A-Za-z0-9 ', ''): "-",
            email.first_name.present? ? email.first_name.to_s.tr('^A-Za-z0-9 ', '')  : "-",
            email.last_name.present? ? email.last_name.to_s.tr('^A-Za-z0-9 ', '') : "-",
            email.position.present? ? email.position.to_s.tr('^A-Za-z0-9 ', ''): "-" ,
            email.email.present? ? email.email.to_s: "-"  ,
            email.status.present? ? email.status.to_s.tr('^A-Za-z0-9 ', '')  : "-",
            email.address_type.present? ? email.address_type.to_s.tr('^A-Za-z0-9 ', '') : "-",
            email.twitter.present? ? email.twitter.to_s.tr('^A-Za-z0-9 ', ''): "-", ].to_csv( row_sep: nil )

app/views/home/get_emails.js.erb
$('#get_emails').html("<%= escape_javascript(render '/home/get_emails') %>")
$('#waiting_bar').modal("hide")
$('#get_emails').modal("show")

app/views/home/index.html.haml
.container.col-lg-12
  .jumbotron
    %h3 Welcome to SalesBot
    .row.col-lg-5
      = form_tag(crawl_path , remote: :true , id: "search_form") do
        .col-lg-4
          = text_field_tag 'keyword' ,"", class: 'form-control' , placeholder: "Enter Keyword"
        .col-lg-5
          = text_field_tag 'city' ,"", class: 'form-control' , placeholder: "Enter City/State"
        = submit_tag 'Get Started' , class: "btn btn-success" , onclick: "return show_waiting_bar();",data: {disable_with: 'loading...'}
    .row.col-lg-3
      = form_tag import_csv_path, multipart: true ,id: "import_csv" ,remote: :true do
        .col-lg-5
          = file_field_tag :file , class: "btn " , onchange: "enable_button('import_csv_submit');"
        .col-lg-2
        .col-lg-4.pull-right
          = submit_tag "Import CSV" , class: "btn" , id: "import_csv_submit"  ,disabled: true, onclick: "return show_waiting_bar();"
    #job_postings
      = render :partial => "home/job_postings" , locals:{jobs: @batches.last.present?  ? @batches.last.jobs : []  }