config/routes.rb
Rails.application.routes.draw do
  resources :companies
  resources :jobs
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "home#index"
  match "/home/crawl",  via: [ :post] , as: :crawl
  get "/home/refresh-batch" => "home#crawl" , as: :refresh_batch
  get	"/home/web-address/:company_name" => "home#web_address", as: :web_address
  get "/home/get-domains/:batch_id" => "home#get_domains", as: :get_domains
  get "/home/get_company/:id" => "home#get_company", as: :get_company
  get "/home/get-emails/:id(/:job_id)" => "home#get_emails", as: :get_emails
  get "/home/get-all-emails/:batch_id" => "home#get_all_emails", as: :get_all_emails
  get "/home/csv-download/:batch_id" => "home#csv_download", as: :csv_download
  get "/home/job-csv-download/:job_id" => "home#job_csv_download", as: :job_csv_download
  get "/:batch_id"=> "home#index" , as: :active_batch
  post "/companies/import-csv" => "companies#import_csv", as: :import_csv



end

app/models/company.rb
require 'snovio'
class Company < ApplicationRecord
  has_many :jobs ,dependent: :destroy
  has_one :domain_search ,dependent: :destroy
  has_many :batch_companies
  has_many :batches , through: :batch_companies

  def create_domain_search
    access_token = Snovio.get_access_token
    self.domain_search = DomainSearch.find_or_initialize_by(domain: self.trim_web_address)
    domain_search = self.domain_search
    begin
      @emails = Snovio.get_emails domain_search.domain , access_token
      domains_search_emails = domain_search.emails
      @emails["emails"].each do |email|
        if !(domains_search_emails.include? "#{email}")
            domain_search.emails.create!(email: email["email"]) do |email_row|
              email_row.address_type = email["type"]
              email_row.status = email["status"]
              email_row.first_name = email["firstName"]
              email_row.last_name = email["lastName"]
              email_row.position = email["position"]
              email_row.source_page = email["sourcePage"]
              email_row.twitter = email["twitter"]
            end
        end
      end
    rescue
        puts "-------_skipping---- #{domain_search}------===================-"
    end
    domain_search.emails
  end
  def trim_web_address
    web_address = self.web_address.include?("http") ?  (Addressable::URI.parse(self.web_address).host.to_s) : (self.web_address)
    web_address.slice! "www."
    web_address
  end
  def self.check
    Snovio.get_access_token
  end
  def self.import file
    all_company_web_addresses = all.pluck(:web_address)
    xlsx = Roo::Spreadsheet.open(file)
    spreadsheet = xlsx.sheet(0)
    company_name = spreadsheet.row(1).first
    company_url = spreadsheet.row(1).second
    puts "---company_url present  ---- #{company_url}-------------------------------"
    batch = Batch.create(batch_type: "import")
    spreadsheet.each(c: company_name, u: company_url) do |row|
      if !(all_company_web_addresses.include? row[:u] )
        this_company = batch.companies.find_or_create_by!(:name => row[:c] ) do |company|
          company.web_address = row[:u]
        end

        this_company.create_domain_search
      end
    end
  end
  # def self.import file
  #   all_company_web_addresses = all.pluck(:web_address)
  #   xlsx = Roo::Spreadsheet.open(file)
  #   spreadsheet = xlsx.sheet(0)
  #   company_name = spreadsheet.row(1).first
  #   # company_url = spreadsheet.row(1).second
  #   batch = Batch.create(batch_type: "import")
  #   spreadsheet.each(c: company_name) do |row|
  #     if !(all_company_web_addresses.include? row[:u] )
  #       this_company = batch.companies.find_or_create_by!(:name => row[:c] )# do |company|
  #         # company.web_address = row[:u]
  #       # end
  #       this_company.create_domain_search
  #     end
  #   end
  # end
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
    @active_batch = Batch.unscoped.find_by_id(params[:active_batch])
    respond_to do |format|
      format.js do

      end
      format.html
    end
  end
  def import_csv
    begin
    Company.import(params[:file])
    render js: "$('#waiting_bar').modal('hide'); alert('import Successfull')"
    rescue => error
      puts "-------------+++++++#{error.inspect}-----------------------"
      render js: "$('#waiting_bar').modal('hide'); alert('Something went wrong')"
    end

  end
  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    @active_batch = Batch.unscoped.find_by_id(params[:batch_id])
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to active_batch_path(params[:batch_id]), notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
        format.js {  redirect_to active_batch_path(params[:batch_id]), notice: 'Company was successfully updated.' }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }

      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :web_address, :invalid_address, :active_batch)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_edit_form.html.haml
.modal-dialog{:role => "document"}
  .modal-content
    .modal-header
      %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
        %span{"aria-hidden" => "true"} x
      %h3.modal-title
        Edit Company
      .col-lg-10
      -#= (link_to "Download CSV", job_csv_download_path(@job.id, format: :csv) , class: " pull")
    .modal-body.emails-table
      = form_for @company  do |f|
        - if @company.errors.any?
          #error_explanation
            %h2= "#{pluralize(@company.errors.count, "error")} prohibited this company from being saved:"
            %ul
              - @company.errors.full_messages.each do |message|
                %li= message
        = hidden_field_tag :batch_id ,  @active_batch.id
        .field1
          = f.label :name , class: "control-label"
          = f.text_field :name, class: "form-control"
        .field1
          = f.label :web_address
          = f.text_field :web_address ,class: "form-control"
        .checkbox.field
          %label
            = f.check_box :invalid_address, class: "checkbox"
            %b Mark Invalid
        .actions1
          = f.submit 'Update',class: "btn btn-primary "

app/views/companies/_form.html.haml
= form_for @company do |f|
  - if @company.errors.any?
    #error_explanation
      %h2= "#{pluralize(@company.errors.count, "error")} prohibited this company from being saved:"
      %ul
        - @company.errors.full_messages.each do |message|
          %li= message

  .field1
    = f.label :name
    = f.text_field :name
  .field1
    = f.label :web_address
    = f.text_field :web_address
  .field1
    = f.label :invalid_address
    = f.check_box :invalid_address
  .actions1
    = f.submit 'Save'

app/views/companies/edit.html.haml
%h1 Editing company

= render 'form'

= link_to 'Show', @company
\|
= link_to 'Back', companies_path

app/views/companies/edit.js.erb
$('#get_company').html("<%= escape_javascript(render 'companies/edit_form') %>")
$('#get_company').modal("show")

app/views/companies/index.html.haml
%h1 Listing companies

%table
  %thead
    %tr
      %th Name
      %th Web address
      %th
      %th
      %th

  %tbody
    - @companies.each do |company|
      %tr
        %td= company.name
        %td= company.web_address
        %td= link_to 'Show', company
        %td= link_to 'Edit', edit_company_path(company)
        %td= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Company', new_company_path

app/views/companies/new.html.haml
%h1 New company

= render 'form'

= link_to 'Back', companies_path

app/views/companies/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @company.name
%p
  %b Web address:
  = @company.web_address

= link_to 'Edit', edit_company_path(@company)
\|
= link_to 'Back', root_path